"""成就定义数据 - 8大类共43项成就的定义"""

from typing import List
from dataclasses import dataclass, field
from enum import Enum


class AchievementCategory(Enum):
    GAMER = "gamer"
    MODDER = "modder"
    SERVER = "server"
    BACKUP = "backup"
    ONLINE = "online"
    AGENT = "agent"
    PERSONALIZE = "personalize"
    ADVANCED = "advanced"


CATEGORY_ORDER = [
    AchievementCategory.GAMER,
    AchievementCategory.MODDER,
    AchievementCategory.SERVER,
    AchievementCategory.BACKUP,
    AchievementCategory.ONLINE,
    AchievementCategory.AGENT,
    AchievementCategory.PERSONALIZE,
    AchievementCategory.ADVANCED,
]


@dataclass
class AchievementDef:
    achievement_id: str
    category: AchievementCategory
    i18n_key: str
    desc_i18n_key: str
    icon: str
    stages: List[int] = field(default_factory=list)
    stage_names: List[str] = field(default_factory=list)
    trigger_type: str = "increment"


ACHIEVEMENTS: List[AchievementDef] = [
    # ═══════════ 🎮 游戏玩家 ═══════════
    AchievementDef(
        achievement_id="gamer_first_launch",
        category=AchievementCategory.GAMER,
        i18n_key="ach_gamer_first_launch",
        desc_i18n_key="ach_gamer_first_launch_desc",
        icon="🎮",
        stages=[1],
        stage_names=["启程"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="gamer_version_collector",
        category=AchievementCategory.GAMER,
        i18n_key="ach_gamer_version_collector",
        desc_i18n_key="ach_gamer_version_collector_desc",
        icon="📦",
        stages=[10, 30, 50],
        stage_names=["版本收藏家 I", "版本收藏家 II", "版本收藏家 III"],
        trigger_type="set",
    ),
    AchievementDef(
        achievement_id="gamer_cross_era",
        category=AchievementCategory.GAMER,
        i18n_key="ach_gamer_cross_era",
        desc_i18n_key="ach_gamer_cross_era_desc",
        icon="⏳",
        stages=[1],
        stage_names=["跨越时空"],
        trigger_type="check",
    ),
    AchievementDef(
        achievement_id="gamer_retro",
        category=AchievementCategory.GAMER,
        i18n_key="ach_gamer_retro",
        desc_i18n_key="ach_gamer_retro_desc",
        icon="🕹️",
        stages=[1],
        stage_names=["怀旧风"],
        trigger_type="check",
    ),
    AchievementDef(
        achievement_id="gamer_frontier",
        category=AchievementCategory.GAMER,
        i18n_key="ach_gamer_frontier",
        desc_i18n_key="ach_gamer_frontier_desc",
        icon="🚀",
        stages=[1],
        stage_names=["前沿玩家"],
        trigger_type="check",
    ),
    AchievementDef(
        achievement_id="gamer_launch_master",
        category=AchievementCategory.GAMER,
        i18n_key="ach_gamer_launch_master",
        desc_i18n_key="ach_gamer_launch_master_desc",
        icon="🏆",
        stages=[50, 100, 500],
        stage_names=["启动大师 I", "启动大师 II", "启动大师 III"],
        trigger_type="increment",
    ),

    # ═══════════ 🔧 模组玩家 ═══════════
    AchievementDef(
        achievement_id="modder_first_mod",
        category=AchievementCategory.MODDER,
        i18n_key="ach_modder_first_mod",
        desc_i18n_key="ach_modder_first_mod_desc",
        icon="🧩",
        stages=[1],
        stage_names=["第一个模组"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="modder_mod_expert",
        category=AchievementCategory.MODDER,
        i18n_key="ach_modder_mod_expert",
        desc_i18n_key="ach_modder_mod_expert_desc",
        icon="⚙️",
        stages=[20, 50, 100],
        stage_names=["模组达人 I", "模组达人 II", "模组达人 III"],
        trigger_type="set",
    ),
    AchievementDef(
        achievement_id="modder_full_house",
        category=AchievementCategory.MODDER,
        i18n_key="ach_modder_full_house",
        desc_i18n_key="ach_modder_full_house_desc",
        icon="🏠",
        stages=[1],
        stage_names=["全家福"],
        trigger_type="check",
    ),
    AchievementDef(
        achievement_id="modder_diy",
        category=AchievementCategory.MODDER,
        i18n_key="ach_modder_diy",
        desc_i18n_key="ach_modder_diy_desc",
        icon="🛠️",
        stages=[1],
        stage_names=["自己动手"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="modder_lazy",
        category=AchievementCategory.MODDER,
        i18n_key="ach_modder_lazy",
        desc_i18n_key="ach_modder_lazy_desc",
        icon="🦥",
        stages=[1],
        stage_names=["懒人福利"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="modder_dependency_expert",
        category=AchievementCategory.MODDER,
        i18n_key="ach_modder_dependency_expert",
        desc_i18n_key="ach_modder_dependency_expert_desc",
        icon="🔗",
        stages=[1],
        stage_names=["依赖专家"],
        trigger_type="increment",
    ),

    # ═══════════ 🖥️ 服务器主 ═══════════
    AchievementDef(
        achievement_id="server_first_server",
        category=AchievementCategory.SERVER,
        i18n_key="ach_server_first_server",
        desc_i18n_key="ach_server_first_server_desc",
        icon="🖥️",
        stages=[1],
        stage_names=["开服小白"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="server_admin",
        category=AchievementCategory.SERVER,
        i18n_key="ach_server_admin",
        desc_i18n_key="ach_server_admin_desc",
        icon="👑",
        stages=[1],
        stage_names=["管理员"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="server_modpack_server",
        category=AchievementCategory.SERVER,
        i18n_key="ach_server_modpack_server",
        desc_i18n_key="ach_server_modpack_server_desc",
        icon="📦",
        stages=[1],
        stage_names=["整合包开服"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="server_uptime",
        category=AchievementCategory.SERVER,
        i18n_key="ach_server_uptime",
        desc_i18n_key="ach_server_uptime_desc",
        icon="⏱️",
        stages=[1, 24, 168],
        stage_names=["常驻主机 I", "常驻主机 II", "常驻主机 III"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="server_cross_play",
        category=AchievementCategory.SERVER,
        i18n_key="ach_server_cross_play",
        desc_i18n_key="ach_server_cross_play_desc",
        icon="🔗",
        stages=[1],
        stage_names=["跨服连动"],
        trigger_type="increment",
    ),

    # ═══════════ 💾 备份习惯 ═══════════
    AchievementDef(
        achievement_id="backup_first_backup",
        category=AchievementCategory.BACKUP,
        i18n_key="ach_backup_first_backup",
        desc_i18n_key="ach_backup_first_backup_desc",
        icon="💾",
        stages=[1],
        stage_names=["保险第一"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="backup_time_machine",
        category=AchievementCategory.BACKUP,
        i18n_key="ach_backup_time_machine",
        desc_i18n_key="ach_backup_time_machine_desc",
        icon="⏰",
        stages=[1],
        stage_names=["时光机"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="backup_mania",
        category=AchievementCategory.BACKUP,
        i18n_key="ach_backup_mania",
        desc_i18n_key="ach_backup_mania_desc",
        icon="📚",
        stages=[5, 20, 50],
        stage_names=["备份狂魔 I", "备份狂魔 II", "备份狂魔 III"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="backup_automation",
        category=AchievementCategory.BACKUP,
        i18n_key="ach_backup_automation",
        desc_i18n_key="ach_backup_automation_desc",
        icon="🤖",
        stages=[1],
        stage_names=["自动化"],
        trigger_type="check",
    ),
    AchievementDef(
        achievement_id="backup_export_share",
        category=AchievementCategory.BACKUP,
        i18n_key="ach_backup_export_share",
        desc_i18n_key="ach_backup_export_share_desc",
        icon="📤",
        stages=[1],
        stage_names=["导出分享"],
        trigger_type="increment",
    ),

    # ═══════════ 🌐 联机玩家 ═══════════
    AchievementDef(
        achievement_id="online_first_online",
        category=AchievementCategory.ONLINE,
        i18n_key="ach_online_first_online",
        desc_i18n_key="ach_online_first_online_desc",
        icon="🌐",
        stages=[1],
        stage_names=["组网初试"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="online_room_owner",
        category=AchievementCategory.ONLINE,
        i18n_key="ach_online_room_owner",
        desc_i18n_key="ach_online_room_owner_desc",
        icon="🏠",
        stages=[1],
        stage_names=["房间主人"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="online_guest",
        category=AchievementCategory.ONLINE,
        i18n_key="ach_online_guest",
        desc_i18n_key="ach_online_guest_desc",
        icon="🚪",
        stages=[1],
        stage_names=["客人来访"],
        trigger_type="increment",
    ),

    # ═══════════ 🤖 AGENT 智能助手 ═══════════
    AchievementDef(
        achievement_id="agent_first_chat",
        category=AchievementCategory.AGENT,
        i18n_key="ach_agent_first_chat",
        desc_i18n_key="ach_agent_first_chat_desc",
        icon="💬",
        stages=[1],
        stage_names=["初次对话"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="agent_nlp_master",
        category=AchievementCategory.AGENT,
        i18n_key="ach_agent_nlp_master",
        desc_i18n_key="ach_agent_nlp_master_desc",
        icon="🎯",
        stages=[1, 10, 50],
        stage_names=["自然语言控 I", "自然语言控 II", "自然语言控 III"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="agent_multi_turn",
        category=AchievementCategory.AGENT,
        i18n_key="ach_agent_multi_turn",
        desc_i18n_key="ach_agent_multi_turn_desc",
        icon="🔄",
        stages=[1],
        stage_names=["多轮对话"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="agent_terminal_warrior",
        category=AchievementCategory.AGENT,
        i18n_key="ach_agent_terminal_warrior",
        desc_i18n_key="ach_agent_terminal_warrior_desc",
        icon="⚡",
        stages=[1],
        stage_names=["终端勇士"],
        trigger_type="increment",
    ),

    # ═══════════ 🎨 个性化 ═══════════
    AchievementDef(
        achievement_id="personalize_skin",
        category=AchievementCategory.PERSONALIZE,
        i18n_key="ach_personalize_skin",
        desc_i18n_key="ach_personalize_skin_desc",
        icon="👤",
        stages=[1],
        stage_names=["换皮肤"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="personalize_rename",
        category=AchievementCategory.PERSONALIZE,
        i18n_key="ach_personalize_rename",
        desc_i18n_key="ach_personalize_rename_desc",
        icon="✏️",
        stages=[1],
        stage_names=["换名字"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="personalize_theme_master",
        category=AchievementCategory.PERSONALIZE,
        i18n_key="ach_personalize_theme_master",
        desc_i18n_key="ach_personalize_theme_master_desc",
        icon="🎨",
        stages=[1],
        stage_names=["主题大师"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="personalize_my_color",
        category=AchievementCategory.PERSONALIZE,
        i18n_key="ach_personalize_my_color",
        desc_i18n_key="ach_personalize_my_color_desc",
        icon="🎲",
        stages=[1],
        stage_names=["我的颜色我做主"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="personalize_version_theme",
        category=AchievementCategory.PERSONALIZE,
        i18n_key="ach_personalize_version_theme",
        desc_i18n_key="ach_personalize_version_theme_desc",
        icon="🌈",
        stages=[1],
        stage_names=["版本色调"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="personalize_import_theme",
        category=AchievementCategory.PERSONALIZE,
        i18n_key="ach_personalize_import_theme",
        desc_i18n_key="ach_personalize_import_theme_desc",
        icon="📥",
        stages=[1],
        stage_names=["导入达人"],
        trigger_type="increment",
    ),

    # ═══════════ ⚡ 高级用户 ═══════════
    AchievementDef(
        achievement_id="advanced_mirror",
        category=AchievementCategory.ADVANCED,
        i18n_key="ach_advanced_mirror",
        desc_i18n_key="ach_advanced_mirror_desc",
        icon="🚀",
        stages=[1],
        stage_names=["镜像飞人"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="advanced_multithread",
        category=AchievementCategory.ADVANCED,
        i18n_key="ach_advanced_multithread",
        desc_i18n_key="ach_advanced_multithread_desc",
        icon="⚡",
        stages=[1],
        stage_names=["多线程王者"],
        trigger_type="check",
    ),
    AchievementDef(
        achievement_id="advanced_polyglot",
        category=AchievementCategory.ADVANCED,
        i18n_key="ach_advanced_polyglot",
        desc_i18n_key="ach_advanced_polyglot_desc",
        icon="🌍",
        stages=[1, 3, 5],
        stage_names=["双语者 I", "双语者 II", "双语者 III"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="advanced_crash_analyst",
        category=AchievementCategory.ADVANCED,
        i18n_key="ach_advanced_crash_analyst",
        desc_i18n_key="ach_advanced_crash_analyst_desc",
        icon="🔍",
        stages=[1],
        stage_names=["崩溃分析师"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="advanced_log_hunter",
        category=AchievementCategory.ADVANCED,
        i18n_key="ach_advanced_log_hunter",
        desc_i18n_key="ach_advanced_log_hunter_desc",
        icon="📋",
        stages=[1],
        stage_names=["日志猎人"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="advanced_updater",
        category=AchievementCategory.ADVANCED,
        i18n_key="ach_advanced_updater",
        desc_i18n_key="ach_advanced_updater_desc",
        icon="🔄",
        stages=[1],
        stage_names=["更新狂"],
        trigger_type="increment",
    ),
    AchievementDef(
        achievement_id="advanced_checkin",
        category=AchievementCategory.ADVANCED,
        i18n_key="ach_advanced_checkin",
        desc_i18n_key="ach_advanced_checkin_desc",
        icon="📅",
        stages=[3, 7, 30],
        stage_names=["签到达人 I", "签到达人 II", "签到达人 III"],
        trigger_type="increment",
    ),
]

CATEGORY_META = {
    AchievementCategory.GAMER: {"i18n_key": "ach_category_gamer", "icon": "🎮"},
    AchievementCategory.MODDER: {"i18n_key": "ach_category_modder", "icon": "🔧"},
    AchievementCategory.SERVER: {"i18n_key": "ach_category_server", "icon": "🖥️"},
    AchievementCategory.BACKUP: {"i18n_key": "ach_category_backup", "icon": "💾"},
    AchievementCategory.ONLINE: {"i18n_key": "ach_category_online", "icon": "🌐"},
    AchievementCategory.AGENT: {"i18n_key": "ach_category_agent", "icon": "🤖"},
    AchievementCategory.PERSONALIZE: {"i18n_key": "ach_category_personalize", "icon": "🎨"},
    AchievementCategory.ADVANCED: {"i18n_key": "ach_category_advanced", "icon": "⚡"},
}
