#!/usr/bin/env bash
# ============================================================
# FMCL Linux 源码安装脚本
# 支持: Debian / Ubuntu / Fedora / RHEL / CentOS / Arch / openSUSE
#
# 用法:
#   curl -fsSL https://raw.githubusercontent.com/Janson20/FMCL/main/scripts/install.sh | bash
#   或
#   ./scripts/install.sh [安装目录]
#
# 默认安装目录: /opt/fmcl
# 自定义目录:   ./scripts/install.sh ~/.local/share/fmcl
# ============================================================
set -euo pipefail

# ── 颜色输出 ──────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
step()  { echo -e "${CYAN}[STEP]${NC}  $*"; }

# ── 参数解析 ──────────────────────────────────────────────
INSTALL_DIR="${1:-/opt/fmcl}"
REPO_URL="https://github.com/Janson20/FMCL.git"
BIN_PATH="/usr/local/bin/fmcl"
DESKTOP_FILE="${HOME}/.local/share/applications/fmcl.desktop"

info "FMCL 安装脚本  |  安装目录: ${INSTALL_DIR}"

# ── 检测 Linux 发行版 ─────────────────────────────────────
detect_distro() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        echo "${ID}"
    else
        error "无法检测 Linux 发行版，请手动安装依赖后重试"
    fi
}

DISTRO=$(detect_distro)
info "检测到发行版: ${DISTRO}"

# ── 检查是否为 root 安装到 /opt ──────────────────────────
if [[ "${INSTALL_DIR}" == /opt/* ]] && [ "$(id -u)" -ne 0 ]; then
    warn "安装到 ${INSTALL_DIR} 需要 root 权限，将使用 sudo 执行后续操作"
    USE_SUDO="sudo"
else
    USE_SUDO=""
fi

# ── 1. 安装系统依赖 ──────────────────────────────────────
step "1/6 安装系统依赖 (git, tkinter 运行库)..."

install_deps_debian() {
    ${USE_SUDO} apt-get update -qq
    ${USE_SUDO} apt-get install -y -qq git python3-tk
}

install_deps_ubuntu() {
    install_deps_debian
}

install_deps_linuxmint() {
    install_deps_debian
}

install_deps_fedora() {
    ${USE_SUDO} dnf install -y git python3-tkinter
}

install_deps_rhel() {
    ${USE_SUDO} dnf install -y git python3-tkinter
}

install_deps_centos() {
    ${USE_SUDO} yum install -y git python3-tkinter
}

install_deps_arch() {
    ${USE_SUDO} pacman -Syu --noconfirm --needed git tk
}

install_deps_manjarolinux() {
    install_deps_arch
}

install_deps_opensuse() {
    ${USE_SUDO} zypper install -y git python3-tk
}

install_deps_opensuse-tumbleweed() {
    install_deps_opensuse
}

# 尝试调用对应函数，失败则跳过（用户可自行安装）
if declare -f "install_deps_${DISTRO}" > /dev/null 2>&1; then
    "install_deps_${DISTRO}"
    info "系统依赖安装完成"
else
    warn "未知发行版 '${DISTRO}'，跳过自动安装系统依赖"
    warn "请手动安装: git, python3-tk (或等效包)"
fi

# ── 2. 安装 uv ──────────────────────────────────────────
step "2/6 安装 uv (Python 包管理器)..."

if command -v uv &>/dev/null; then
    info "uv 已安装: $(uv --version 2>/dev/null || echo 'ok')"
else
    # 官方安装方式: 下载独立二进制
    curl -LsSf https://astral.sh/uv/install.sh | sh
    # 确保 uv 在 PATH 中
    export PATH="${HOME}/.local/bin:${HOME}/.cargo/bin:${PATH}"
    info "uv 安装完成: $(uv --version)"
fi

# ── 3. 克隆项目 ──────────────────────────────────────────
step "3/6 克隆 FMCL 项目到 ${INSTALL_DIR}..."

if [ -d "${INSTALL_DIR}/.git" ]; then
    info "项目目录已存在，执行 git pull 更新..."
    cd "${INSTALL_DIR}"
    git pull --ff-only
else
    if [ -d "${INSTALL_DIR}" ] && [ "$(ls -A "${INSTALL_DIR}" 2>/dev/null)" ]; then
        warn "${INSTALL_DIR} 目录非空且不是 git 仓库，请手动处理后重试"
        exit 1
    fi
    ${USE_SUDO} mkdir -p "${INSTALL_DIR}"
    if [ -n "${USE_SUDO}" ]; then
        ${USE_SUDO} chown "$(id -u):$(id -g)" "${INSTALL_DIR}"
    fi
    git clone "${REPO_URL}" "${INSTALL_DIR}"
    cd "${INSTALL_DIR}"
fi

info "项目已就绪: ${INSTALL_DIR}"

# ── 4. uv sync ───────────────────────────────────────────
step "4/6 安装 Python 依赖 (uv sync)..."

cd "${INSTALL_DIR}"
uv sync
info "Python 依赖安装完成"

# ── 5. 设置 FHS 目录结构 ─────────────────────────────────
step "5/6 设置 Linux FHS 目录..."

${USE_SUDO} mkdir -p /etc/fmcl
${USE_SUDO} mkdir -p /var/log/fmcl

# 确保当前用户拥有这些目录的写权限
if [ -n "${USE_SUDO}" ]; then
    ${USE_SUDO} chown "$(id -u):$(id -g)" /etc/fmcl
    ${USE_SUDO} chown "$(id -u):$(id -g)" /var/log/fmcl
fi

mkdir -p "${HOME}/.minecraft"
mkdir -p "${HOME}/.fmcl"

info "FHS 目录结构创建完成"

# ── 6. 注册 fmcl 命令 ────────────────────────────────────
step "6/6 注册 fmcl 命令..."

FMCL_LAUNCHER=$(cat << EOF
#!/bin/bash
# FMCL Launcher - auto-generated by install.sh
export PATH="\${HOME}/.local/bin:\${HOME}/.cargo/bin:\${PATH}"
cd "${INSTALL_DIR}"
exec uv run python main.py "\$@"
EOF
)

# 写入 /usr/local/bin/fmcl
echo "${FMCL_LAUNCHER}" | ${USE_SUDO} tee "${BIN_PATH}" > /dev/null
${USE_SUDO} chmod +x "${BIN_PATH}"

# ── 可选: 创建桌面入口 ───────────────────────────────────
mkdir -p "$(dirname "${DESKTOP_FILE}")"
cat > "${DESKTOP_FILE}" << DESKTOP_EOF
[Desktop Entry]
Name=FMCL
Comment=Fusion Minecraft Launcher
Exec=${BIN_PATH}
Icon=${INSTALL_DIR}/icon.ico
Terminal=false
Type=Application
Categories=Game;
StartupWMClass=FMCL
DESKTOP_EOF

info "桌面快捷方式已创建: ${DESKTOP_FILE}"

# ── 验证 ─────────────────────────────────────────────────
echo ""
echo "============================================"
echo -e " ${GREEN}FMCL 安装完成!${NC}"
echo "============================================"
echo ""
echo "  安装目录:  ${INSTALL_DIR}"
echo "  fmcl 命令: ${BIN_PATH}"
echo ""
echo "  使用方法:"
echo "    fmcl              # 启动 GUI"
echo "    fmcl -A           # Agent 交互模式"
echo "    fmcl -A \"指令\"    # Agent 单指令模式"
echo ""
echo "  如需更新:"
echo "    cd ${INSTALL_DIR} && git pull && uv sync"
echo ""
echo "  故障排除:"
echo "    查看文档: ${INSTALL_DIR}/docs/TROUBLESHOOTING.md"
echo "============================================"
